### ISSUE TITLE
Email - key revoking process - link should be clickable

### ISSUE THREAD

**Issue by bbusenius** [Argonne-National-Laboratory/meg-server#1]
The email sent should be html and the link should be clickable.

**Comment by JoshuaLyle** [comment]
Please try to revoke your key again. The link should be clickable. What client are you testing with?

**Comment by bbusenius** [comment]
I'm using Thunderbird 45.2.0 on Linux. I just tried again and it still wasn't clickable.

**Comment by JoshuaLyle** [comment]
Alright try one more time

**Comment by bbusenius** [comment]
Yep, it's fixed
